### ISSUE TITLE
Deployment on OpenShift: iot-sse-server service port is incorrect

### ISSUE THREAD

**Issue by gbengataylor** [RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop#8]
When deploying the completed services in a namespace, the iot-sse-server is unavailable. The issue is that the Service resource maps to the incorrect port

Change    https://github.com/RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop/blob/1923c3f1a27c015a8a92c859ba4746d305834e3a/services/iot-sse-server/openshift/svc.yml#L16 

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-sse-server
    app.kubernetes.io/component: iot-sse-server
    app.kubernetes.io/instance: iot-sse-server
    app.kubernetes.io/part-of: iot-sse-server
    app.openshift.io/runtime-version: latest
  name: iot-sse-server
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: iot-sse-server
    deploymentconfig: iot-sse-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
